// import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

// type BuildPdfInput = {
//   destination: string;
//   itinerary: any;
// };

// const TIME_ORDER = ['morning', 'afternoon', 'evening'];

// export async function buildItineraryPdf({
//   destination,
//   itinerary,
// }: BuildPdfInput) {
//   const pdfDoc = await PDFDocument.create();
//   const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

//   const PAGE_WIDTH = 595;
//   const PAGE_HEIGHT = 842;
//   const MARGIN_X = 40;
//   const MARGIN_BOTTOM = 40;

//   let page = pdfDoc.addPage([595, 842]); // A4
//   let y = PAGE_HEIGHT - 60;

//   // COLORS
//   const PRIMARY = rgb(0.18, 0.39, 0.8);
//   const MUTED = rgb(0.45, 0.45, 0.45);
//   const BLACK = rgb(0, 0, 0);
//   const SOFT_BG = rgb(0.95, 0.96, 1);

//   // HELPERS
//   const nextLine = (offset = 16) => {
//     y -= offset;
//   };

//   const ensureSpace = (needed = 60) => {
//     if (y < MARGIN_BOTTOM + needed) {
//       page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
//       y = PAGE_HEIGHT - 60;
//     }
//   };

//   const drawText = (
//     text: string,
//     size = 11,
//     color = BLACK,
//     options: any = {},
//   ) => {
//     page.drawText(text, {
//       x: MARGIN_X,
//       y,
//       size,
//       font,
//       color,
//       ...options,
//     });
//   };

//   // Title

//   drawText(`Trip to ${destination}`, 26, PRIMARY);
//   nextLine(32);

//   drawText(`AI-crafted itinerary by Voyana AI`, 12, MUTED);
//   nextLine(30);

//   // Overview

//   if (itinerary?.overview?.summary) {
//     page.drawRectangle({
//       x: MARGIN_X - 10,
//       y: y - 70,
//       width: PAGE_WIDTH - MARGIN_X * 2 + 20,
//       height: 70,
//       color: SOFT_BG,
//     });

//     drawText('Overview', 15, PRIMARY);
//     nextLine(18);

//     drawText(itinerary.overview.summary, 11, MUTED, {
//       maxWidth: PAGE_WIDTH - MARGIN_X * 2,
//       lineHeight: 14,
//     });

//     nextLine(80);
//   }

//   // Days

//   for (const day of itinerary.days || []) {
//     ensureSpace(80);

//     drawText(`Day ${day.day}`, 17, PRIMARY);
//     nextLine(22);

//     // Local Tip
//     if (day.localTip) {
//       ensureSpace(50);

//       page.drawRectangle({
//         x: MARGIN_X - 6,
//         y: y - 34,
//         width: PAGE_WIDTH - MARGIN_X * 2 + 12,
//         height: 34,
//         color: SOFT_BG,
//       });

//       drawText(`Local tip: ${day.localTip}`, 11, rgb(0.2, 0.2, 0.2), {
//         maxWidth: PAGE_WIDTH - MARGIN_X * 2,
//       });

//       nextLine(46);
//     }

//     // for (const activity of day.activities || []) {
//     //   ensureSpace(90);

//     //   drawText(`• ${activity.name}`, 12, BLACK);
//     //   nextLine(14);

//     //   if (activity.description) {
//     //     drawText(activity.description, 11, MUTED, {
//     //       maxWidth: PAGE_WIDTH - MARGIN_X * 2,
//     //       lineHeight: 14,
//     //     });
//     //     nextLine(16);
//     //   }

//     //   if (activity.location?.address) {
//     //     drawText(
//     //       `Location: ${activity.location.address}`,
//     //       10,
//     //       rgb(0.3, 0.3, 0.3),
//     //     );
//     //     nextLine(16);
//     //   }

//     //   nextLine(6);
//     // }

//     for (const block of TIME_ORDER) {
//       const activities = day.activities?.filter(
//         (a: any) => a.timeBlock === block,
//       );

//       if (!activities?.length) continue;

//       ensureSpace(40);

//       // Time block header
//       const timeLabel = day.dayTimeBlocks?.[block];

//       drawText(
//         `${block.toUpperCase()}${timeLabel ? ` • ${timeLabel}` : ''}`,
//         12,
//         PRIMARY,
//       );
//       nextLine(16);

//       for (const activity of activities) {
//         ensureSpace(80);

//         drawText(`• ${activity.name}`, 12, BLACK);
//         nextLine(14);

//         if (activity.description) {
//           drawText(activity.description, 11, MUTED, {
//             maxWidth: PAGE_WIDTH - MARGIN_X * 2,
//             lineHeight: 14,
//           });
//           nextLine(16);
//         }

//         if (activity.location?.address) {
//           drawText(
//             `Location: ${activity.location.address}`,
//             10,
//             rgb(0.3, 0.3, 0.3),
//           );
//           nextLine(14);
//         }

//         nextLine(6);
//       }

//       nextLine(10);
//     }

//     nextLine(14);
//   }

//   // Footer
//   const pages = pdfDoc.getPages();
//   pages.forEach((p, index) =>
//     p.drawText(
//       `Generated by Voyana AI • Page ${index + 1} of ${pages.length} `,
//       {
//         x: MARGIN_X,
//         y: 20,
//         size: 9,
//         font,
//         color: MUTED,
//       },
//     ),
//   );

//   const pdfBytes = await pdfDoc.save();

//   return pdfBytes;
// }
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

type BuildPdfInput = {
  destination: string;
  itinerary: any;
};

const TIME_ORDER = ['morning', 'afternoon', 'evening'];

export async function buildItineraryPdf({
  destination,
  itinerary,
}: BuildPdfInput) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const PAGE_WIDTH = 595;
  const PAGE_HEIGHT = 842;
  const MARGIN_X = 40;
  const MARGIN_BOTTOM = 60; // Increased for safety

  let page = pdfDoc.addPage([595, 842]);
  let y = PAGE_HEIGHT - 60;

  const PRIMARY = rgb(0.18, 0.39, 0.8);
  const MUTED = rgb(0.45, 0.45, 0.45);
  const BLACK = rgb(0, 0, 0);
  const SOFT_BG = rgb(0.95, 0.96, 1);

  const nextLine = (offset = 16) => {
    y -= offset;
  };

  const ensureSpace = (needed = 60) => {
    if (y < MARGIN_BOTTOM + needed) {
      page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      y = PAGE_HEIGHT - 60;
    }
  };

  /**
   * Enhanced drawText that calculates height used by word-wrapping
   */
  const drawText = (
    text: string,
    size = 11,
    color = BLACK,
    options: any = {},
  ) => {
    const maxWidth = options.maxWidth || PAGE_WIDTH - MARGIN_X * 2;

    page.drawText(text, {
      x: MARGIN_X,
      y,
      size,
      font,
      color,
      maxWidth,
      ...options,
    });

    // Calculate how many lines the text took
    const words = text.split(' ');
    let lineCount = 1;
    let currentLineW = 0;

    words.forEach((word) => {
      const wordWidth = font.widthOfTextAtSize(word + ' ', size);
      if (currentLineW + wordWidth > maxWidth) {
        lineCount++;
        currentLineW = wordWidth;
      } else {
        currentLineW += wordWidth;
      }
    });

    const lineHeight = options.lineHeight || size * 1.2;
    return lineCount * lineHeight;
  };

  // Title
  drawText(`Trip to ${destination}`, 26, PRIMARY);
  nextLine(40);

  drawText(`AI-crafted itinerary by Voyana AI`, 12, MUTED);
  nextLine(40);

  // Overview
  if (itinerary?.overview?.summary) {
    ensureSpace(100);
    const summaryText = itinerary.overview.summary;
    const textHeight = drawText(summaryText, 11, MUTED, { opacity: 0 }); // Pre-calc height

    page.drawRectangle({
      x: MARGIN_X - 10,
      y: y - textHeight - 35,
      width: PAGE_WIDTH - MARGIN_X * 2 + 20,
      height: textHeight + 45,
      color: SOFT_BG,
    });

    drawText('Overview', 15, PRIMARY);
    nextLine(22);
    const used = drawText(summaryText, 11, MUTED, { lineHeight: 14 });
    nextLine(used + 30);
  }

  // Days
  for (const day of itinerary.days || []) {
    ensureSpace(100);

    drawText(`Day ${day.day}`, 17, PRIMARY);
    nextLine(25);

    if (day.localTip) {
      const tipText = `Local tip: ${day.localTip}`;
      const tipHeight = drawText(tipText, 11, BLACK, { opacity: 0 });

      ensureSpace(tipHeight + 20);
      page.drawRectangle({
        x: MARGIN_X - 6,
        y: y - tipHeight - 5,
        width: PAGE_WIDTH - MARGIN_X * 2 + 12,
        height: tipHeight + 15,
        color: SOFT_BG,
      });

      const used = drawText(tipText, 11, rgb(0.2, 0.2, 0.2));
      nextLine(used + 25);
    }

    for (const block of TIME_ORDER) {
      const activities = day.activities?.filter(
        (a: any) => a.timeBlock === block,
      );
      if (!activities?.length) continue;

      ensureSpace(50);
      const timeLabel = day.dayTimeBlocks?.[block];
      drawText(
        `${block.toUpperCase()}${timeLabel ? ` • ${timeLabel}` : ''}`,
        12,
        PRIMARY,
      );
      nextLine(20);

      for (const activity of activities) {
        ensureSpace(60);
        drawText(`• ${activity.name}`, 12, BLACK);
        nextLine(16);

        if (activity.description) {
          const used = drawText(activity.description, 11, MUTED, {
            lineHeight: 14,
          });
          nextLine(used + 5);
        }

        if (activity.location?.address) {
          const used = drawText(
            `Location: ${activity.location.address}`,
            10,
            rgb(0.3, 0.3, 0.3),
          );
          nextLine(used + 5);
        }
        nextLine(10);
      }
    }
    nextLine(20);
  }

  // Footer
  const pages = pdfDoc.getPages();
  pages.forEach((p, index) =>
    p.drawText(
      `Generated by Voyana AI • Page ${index + 1} of ${pages.length}`,
      {
        x: MARGIN_X,
        y: 25,
        size: 9,
        font,
        color: MUTED,
      },
    ),
  );

  return await pdfDoc.save();
}
