import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

type BuildPdfInput = {
  destination: string;
  itinerary: any;
};

export async function buildItineraryPdf({
  destination,
  itinerary,
}: BuildPdfInput) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const PAGE_WIDTH = 595;
  const PAGE_HEIGHT = 842;
  const MARGIN_X = 40;
  const MARGIN_BOTTOM = 40;

  let page = pdfDoc.addPage([595, 842]); // A4
  let y = PAGE_HEIGHT - 60;

  // COLORS
  const PRIMARY = rgb(0.18, 0.39, 0.8);
  const MUTED = rgb(0.45, 0.45, 0.45);
  const BLACK = rgb(0, 0, 0);
  const SOFT_BG = rgb(0.95, 0.96, 1);

  // HELPERS
  const nextLine = (offset = 16) => {
    y -= offset;
  };

  const ensureSpace = (needed = 60) => {
    if (y < MARGIN_BOTTOM + needed) {
      page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      y = PAGE_HEIGHT - 60;
    }
  };

  const drawText = (
    text: string,
    size = 11,
    color = BLACK,
    options: any = {},
  ) => {
    page.drawText(text, {
      x: MARGIN_X,
      y,
      size,
      font,
      color,
      ...options,
    });
  };

  // Title

  drawText(`Trip to ${destination}`, 26, PRIMARY);
  nextLine(32);

  drawText(`AI-crafted itinerary by Voyana AI`, 12, MUTED);
  nextLine(30);

  // Overview

  if (itinerary?.overview?.summary) {
    page.drawRectangle({
      x: MARGIN_X - 10,
      y: y - 70,
      width: PAGE_WIDTH - MARGIN_X * 2 + 20,
      height: 70,
      color: SOFT_BG,
    });

    drawText('Overview', 15, PRIMARY);
    nextLine(18);

    drawText(itinerary.overview.summary, 11, MUTED, {
      maxWidth: PAGE_WIDTH - MARGIN_X * 2,
      lineHeight: 14,
    });

    nextLine(80);
  }

  // Days

  for (const day of itinerary.days || []) {
    ensureSpace(80);

    drawText(`Day ${day.day}`, 17, PRIMARY);
    nextLine(22);

    for (const activity of day.activities || []) {
      ensureSpace(90);

      drawText(`• ${activity.name}`, 12, BLACK);
      nextLine(14);

      if (activity.description) {
        drawText(activity.description, 11, MUTED, {
          maxWidth: PAGE_WIDTH - MARGIN_X * 2,
          lineHeight: 14,
        });
        nextLine(16);
      }

      if (activity.location?.address) {
        drawText(
          `Location: ${activity.location.address}`,
          10,
          rgb(0.3, 0.3, 0.3),
        );
        nextLine(16);
      }

      nextLine(6);
    }

    nextLine(14);
  }

  // Footer
  const pages = pdfDoc.getPages();
  pages.forEach((p, index) =>
    p.drawText(
      `Generated by Voyana AI • Page ${index + 1} of ${pages.length} `,
      {
        x: MARGIN_X,
        y: 20,
        size: 9,
        font,
        color: MUTED,
      },
    ),
  );

  const pdfBytes = await pdfDoc.save();

  return pdfBytes;
}
